---
homebrew_installed_packages:
  - dockutil

dockitems_to_remove:
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iTunes
  - iBooks
  - App Store
  - System Preferences
  - Calendar
  - Siri

dockitems_to_persist:
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
    pos: 1
  - name: Firefox
    path: "/Applications/Firefox.app"
    pos: 2
  - name: Safari
    path: /Applications/Safari.app
    pos: 3
  - name: VirtualBox
    path: /Applications/VirtualBox.app
    pos: 4
  - name: Terminal
    path: /Applications/Utilities/Terminal.app
    pos: 5
  - name: Launchpad
    path: /Applications/Utilities/Launchpad.app
    pos: 6
  - name: Mail
    path: /Applications/Main.app
    pos: 7
