---
- import_tasks: terminal.yml

- name: Install npm packages
  npm:  name={{ item }} global=yes
  with_items: "{{ npm_packages }}"
  changed_when: false

- name: Create Software/bin directory
  file:
    path: "{{ user_path }}/Software/bin"
    state: directory
    mode: 0755

- name: Create Projects directory
  file:
    path: "{{ user_path }}/Projects"
    state: directory
    mode: 0755
